//
// AudienceListDataSourceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AudienceListDataSourceRequest: Codable {

    public enum ModelType: String, Codable { 
        case report = "REPORT"
        case audienceList = "AUDIENCE_LIST"
        case fileAsset = "FILE_ASSET"
    }
    public var type: ModelType?
    public var audienceListId: String?

    public init(type: ModelType? = nil, audienceListId: String? = nil) {
        self.type = type
        self.audienceListId = audienceListId
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case audienceListId = "audience_list_id"
    }

}
