//
// Authorization.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Authorization: Codable {

    public var personId: String?
    public var scopes: [String]?
    public var accessToken: String?
    public var clientId: String?

    public init(personId: String? = nil, scopes: [String]? = nil, accessToken: String? = nil, clientId: String? = nil) {
        self.personId = personId
        self.scopes = scopes
        self.accessToken = accessToken
        self.clientId = clientId
    }


}
