//
// BatchJobResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BatchJobResponse: Codable {

    public enum Status: String, Codable { 
        case pending = "PENDING"
        case inProgress = "IN_PROGRESS"
        case dispatching = "DISPATCHING"
        case done = "DONE"
        case failed = "FAILED"
        case canceled = "CANCELED"
        case expired = "EXPIRED"
    }
    public var _id: String?
    public var eventName: String?
    public var createdDate: Date?
    public var startedDate: Date?
    public var completedDate: Date?
    public var status: Status?
    public var name: String?
    public var tags: [String]?
    public var eventData: [String:String]?
    public var eventColumns: [String]?
    public var downloadUri: String?
    public var dataSource: DataSourceResponse?
    public var successRows: Int64?
    public var failedRows: Int64?
    public var topicName: String?

    public init(_id: String? = nil, eventName: String? = nil, createdDate: Date? = nil, startedDate: Date? = nil, completedDate: Date? = nil, status: Status? = nil, name: String? = nil, tags: [String]? = nil, eventData: [String:String]? = nil, eventColumns: [String]? = nil, downloadUri: String? = nil, dataSource: DataSourceResponse? = nil, successRows: Int64? = nil, failedRows: Int64? = nil, topicName: String? = nil) {
        self._id = _id
        self.eventName = eventName
        self.createdDate = createdDate
        self.startedDate = startedDate
        self.completedDate = completedDate
        self.status = status
        self.name = name
        self.tags = tags
        self.eventData = eventData
        self.eventColumns = eventColumns
        self.downloadUri = downloadUri
        self.dataSource = dataSource
        self.successRows = successRows
        self.failedRows = failedRows
        self.topicName = topicName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case eventName = "event_name"
        case createdDate = "created_date"
        case startedDate = "started_date"
        case completedDate = "completed_date"
        case status
        case name
        case tags
        case eventData = "event_data"
        case eventColumns = "event_columns"
        case downloadUri = "download_uri"
        case dataSource = "data_source"
        case successRows = "success_rows"
        case failedRows = "failed_rows"
        case topicName = "topic_name"
    }

}
