//
// BatchJobFormatInfoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BatchJobFormatInfoResponse: Codable {

    public var contentLength: Int64?
    public var totalRows: Int64?

    public init(contentLength: Int64? = nil, totalRows: Int64? = nil) {
        self.contentLength = contentLength
        self.totalRows = totalRows
    }

    public enum CodingKeys: String, CodingKey { 
        case contentLength = "content_length"
        case totalRows = "total_rows"
    }

}
