//
// BatchJobCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BatchJobCreateRequest: Codable {

    public var name: String?
    public var eventName: String?
    public var tags: [String]?
    public var eventData: [String:String]?
    public var eventColumns: [String]?
    public var dataSource: DataSourceRequest?

    public init(name: String? = nil, eventName: String? = nil, tags: [String]? = nil, eventData: [String:String]? = nil, eventColumns: [String]? = nil, dataSource: DataSourceRequest? = nil) {
        self.name = name
        self.eventName = eventName
        self.tags = tags
        self.eventData = eventData
        self.eventColumns = eventColumns
        self.dataSource = dataSource
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case eventName = "event_name"
        case tags
        case eventData = "event_data"
        case eventColumns = "event_columns"
        case dataSource = "data_source"
    }

}
