//
// CampaignBuildtimeContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignBuildtimeContext: Codable {

    public var variableContext: VariableContext?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(variableContext: VariableContext? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.variableContext = variableContext
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
