//
// ClientContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientContext: Codable {

    public var timezone: String?
    public var clientId: String?
    public var clientShortName: String?

    public init(timezone: String? = nil, clientId: String? = nil, clientShortName: String? = nil) {
        self.timezone = timezone
        self.clientId = clientId
        self.clientShortName = clientShortName
    }


}
