//
// ClientDomainContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientDomainContext: Codable {

    public var clientDomain: String?
    public var clientDomainId: String?

    public init(clientDomain: String? = nil, clientDomainId: String? = nil) {
        self.clientDomain = clientDomain
        self.clientDomainId = clientDomainId
    }


}
