//
// ClientKey.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientKey: Codable {

    public var algorithm: String?
    public var key: String?

    public init(algorithm: String? = nil, key: String? = nil) {
        self.algorithm = algorithm
        self.key = key
    }


}
