//
// CreateTokenRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateTokenRequest: Codable {

    public var durationSeconds: Int64?
    public var jwt: String?
    public var email: String?

    public init(durationSeconds: Int64? = nil, jwt: String? = nil, email: String? = nil) {
        self.durationSeconds = durationSeconds
        self.jwt = jwt
        self.email = email
    }

    public enum CodingKeys: String, CodingKey { 
        case durationSeconds = "duration_seconds"
        case jwt
        case email
    }

}
