//
// CreativeMetricRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreativeMetricRequest: Codable {

    public enum MetricType: String, Codable { 
        case histogram = "HISTOGRAM"
        case counter = "COUNTER"
    }
    public var key: String?
    public var metricType: MetricType?
    public var value: Int64?

    public init(key: String? = nil, metricType: MetricType? = nil, value: Int64? = nil) {
        self.key = key
        self.metricType = metricType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case key
        case metricType = "metric_type"
        case value
    }

}
