//
// CreateCreativeLogResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateCreativeLogResponse: Codable {

    public var pollingId: String?

    public init(pollingId: String? = nil) {
        self.pollingId = pollingId
    }

    public enum CodingKeys: String, CodingKey { 
        case pollingId = "polling_id"
    }

}
