//
// DashboardReportTypeUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DashboardReportTypeUpdateRequest: Codable {

    public enum ModelType: String, Codable { 
        case sql = "SQL"
        case spark = "SPARK"
        case dashboard = "DASHBOARD"
        case configured = "CONFIGURED"
    }
    public var type: ModelType?
    public var tags: [ReportTypeTagRequest]?

    public init(type: ModelType? = nil, tags: [ReportTypeTagRequest]? = nil) {
        self.type = type
        self.tags = tags
    }


}
