//
// EvaluationResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EvaluationResult: Codable {

    public var resultCode: String?
    public var message: String?
    public var parameters: [String:String]?
    public var passed: Bool?

    public init(resultCode: String? = nil, message: String? = nil, parameters: [String:String]? = nil, passed: Bool? = nil) {
        self.resultCode = resultCode
        self.message = message
        self.parameters = parameters
        self.passed = passed
    }


}
