//
// EvaluationResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EvaluationResult: Codable {

    public var passed: Bool?
    public var resultCode: String?
    public var message: String?
    public var parameters: [String:String]?

    public init(passed: Bool? = nil, resultCode: String? = nil, message: String? = nil, parameters: [String:String]? = nil) {
        self.passed = passed
        self.resultCode = resultCode
        self.message = message
        self.parameters = parameters
    }


}
