//
// EvaluationResultBuilder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EvaluationResultBuilder: Codable {

    public var evaluationResults: [EvaluationResult]?

    public init(evaluationResults: [EvaluationResult]? = nil) {
        self.evaluationResults = evaluationResults
    }


}
