//
// EventContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventContext: Codable {

    public var sourceGeoIps: [GeoIp]?

    public init(sourceGeoIps: [GeoIp]? = nil) {
        self.sourceGeoIps = sourceGeoIps
    }


}
