//
// EventData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventData: Codable {

    public enum Source: String, Codable { 
        case jwt = "JWT"
        case prehandler = "PREHANDLER"
        case requestBody = "REQUEST_BODY"
        case requestQueryParameter = "REQUEST_QUERY_PARAMETER"
        case backend = "BACKEND"
        case expiredJwt = "EXPIRED_JWT"
    }
    public var source: Source?
    public var name: String?
    public var value: String?
    public var verified: Bool?

    public init(source: Source? = nil, name: String? = nil, value: String? = nil, verified: Bool? = nil) {
        self.source = source
        self.name = name
        self.value = value
        self.verified = verified
    }


}
