//
// ExpressionActionCommandContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExpressionActionCommandContext: Codable {

    public var data: [String:String]?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?
    public var person: Person?

    public init(data: [String:String]? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil, person: Person? = nil) {
        self.data = data
        self.globalServices = globalServices
        self.clientContext = clientContext
        self.person = person
    }


}
