//
// FileAssetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileAssetResponse: Codable {

    public enum Format: String, Codable { 
        case csv = "CSV"
        case json = "JSON"
        case psv = "PSV"
    }
    public var _id: String?
    public var name: String?
    public var tags: [String]?
    public var format: Format?
    public var createdDate: Date?
    public var userId: String?
    public var size: Int64?

    public init(_id: String? = nil, name: String? = nil, tags: [String]? = nil, format: Format? = nil, createdDate: Date? = nil, userId: String? = nil, size: Int64? = nil) {
        self._id = _id
        self.name = name
        self.tags = tags
        self.format = format
        self.createdDate = createdDate
        self.userId = userId
        self.size = size
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case tags
        case format
        case createdDate = "created_date"
        case userId = "user_id"
        case size
    }

}
