//
// FileAssetRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileAssetRequest: Codable {

    public var fileAssetMetadata: FileAssetMetadata?
    public var fileInputStreamRequest: FileInputStreamRequest?

    public init(fileAssetMetadata: FileAssetMetadata? = nil, fileInputStreamRequest: FileInputStreamRequest? = nil) {
        self.fileAssetMetadata = fileAssetMetadata
        self.fileInputStreamRequest = fileInputStreamRequest
    }


}
