//
// FileAssetMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileAssetMetadata: Codable {

    public enum Format: String, Codable { 
        case csv = "CSV"
        case json = "JSON"
        case psv = "PSV"
    }
    public var name: String?
    public var tags: [String]?
    public var format: Format?

    public init(name: String? = nil, tags: [String]? = nil, format: Format? = nil) {
        self.name = name
        self.tags = tags
        self.format = format
    }


}
