//
// FileInputStreamRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileInputStreamRequest: Codable {

    public var inputStream: String?
    public var attributes: FileAttributes?

    public init(inputStream: String? = nil, attributes: FileAttributes? = nil) {
        self.inputStream = inputStream
        self.attributes = attributes
    }


}
