//
// FlowStepBuildtimeContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlowStepBuildtimeContext: Codable {

    public var stepName: String?
    public var variableContext: VariableContext?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(stepName: String? = nil, variableContext: VariableContext? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.stepName = stepName
        self.variableContext = variableContext
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
