//
// GeoIp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GeoIp: Codable {

    public var location: Location?
    public var state: State?
    public var country: Country?
    public var city: City?
    public var ipAddress: String?

    public init(location: Location? = nil, state: State? = nil, country: Country? = nil, city: City? = nil, ipAddress: String? = nil) {
        self.location = location
        self.state = state
        self.country = country
        self.city = city
        self.ipAddress = ipAddress
    }


}
