//
// GlobalContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GlobalContext: Codable {

    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
