//
// InputEventLabel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InputEventLabel: Codable {

    public var name: String?
    public var _required: Bool?

    public init(name: String? = nil, _required: Bool? = nil) {
        self.name = name
        self._required = _required
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _required = "required"
    }

}
