//
// InputRecord.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InputRecord: Codable {

    public var deviceProfileId: String?
    public var identityProfileId: String?
    public var locale: String?
    public var name: String?
    public var _id: String?
    public var data: [String:String]?
    public var container: String?
    public var clientId: String?
    public var personId: String?
    public var apiType: String?
    public var userId: String?
    public var eventTime: String?
    public var requestTime: String?
    public var userAgent: String?

    public init(deviceProfileId: String? = nil, identityProfileId: String? = nil, locale: String? = nil, name: String? = nil, _id: String? = nil, data: [String:String]? = nil, container: String? = nil, clientId: String? = nil, personId: String? = nil, apiType: String? = nil, userId: String? = nil, eventTime: String? = nil, requestTime: String? = nil, userAgent: String? = nil) {
        self.deviceProfileId = deviceProfileId
        self.identityProfileId = identityProfileId
        self.locale = locale
        self.name = name
        self._id = _id
        self.data = data
        self.container = container
        self.clientId = clientId
        self.personId = personId
        self.apiType = apiType
        self.userId = userId
        self.eventTime = eventTime
        self.requestTime = requestTime
        self.userAgent = userAgent
    }

    public enum CodingKeys: String, CodingKey { 
        case deviceProfileId
        case identityProfileId
        case locale
        case name
        case _id = "id"
        case data
        case container
        case clientId
        case personId
        case apiType
        case userId
        case eventTime
        case requestTime
        case userAgent
    }

}
