//
// InputEventLocale.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InputEventLocale: Codable {

    public var userSpecified: String?
    public var lastBrowser: String?

    public init(userSpecified: String? = nil, lastBrowser: String? = nil) {
        self.userSpecified = userSpecified
        self.lastBrowser = lastBrowser
    }


}
