//
// LegacyQualityRuleTriggerContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LegacyQualityRuleTriggerContext: Codable {

    public var resultBuilder: EvaluationResultBuilder?
    public var bestReferral: PersonReferral?
    public var friendController: Bool?
    public var person: Person?
    public var targetingContext: TargetingContext?
    public var causeEvent: ConsumerEvent?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(resultBuilder: EvaluationResultBuilder? = nil, bestReferral: PersonReferral? = nil, friendController: Bool? = nil, person: Person? = nil, targetingContext: TargetingContext? = nil, causeEvent: ConsumerEvent? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.resultBuilder = resultBuilder
        self.bestReferral = bestReferral
        self.friendController = friendController
        self.person = person
        self.targetingContext = targetingContext
        self.causeEvent = causeEvent
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
