//
// PersonContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonContext: Codable {

    public var person: Person?

    public init(person: Person? = nil) {
        self.person = person
    }


}
