//
// Person.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Person: Codable {

    public var recentAssociatedFriends: [PersonReferral]?
    public var recentAssociatedAdvocates: [PersonReferral]?
    public var _id: String?
    public var locale: String?
    public var data: [String:String]?
    public var email: String?
    public var normalizedEmail: String?
    public var steps: [PersonStep]?
    public var firstName: String?
    public var lastName: String?
    public var partnerUserId: String?
    public var preferredLocale: String?
    public var rewards: [PersonReward]?
    public var publicData: [String:String]?
    public var shareables: [Shareable]?
    public var privateData: [String:String]?
    public var recentRequestContexts: [RequestContext]?
    public var displacedPersonId: String?
    public var blocked: Bool?

    public init(recentAssociatedFriends: [PersonReferral]? = nil, recentAssociatedAdvocates: [PersonReferral]? = nil, _id: String? = nil, locale: String? = nil, data: [String:String]? = nil, email: String? = nil, normalizedEmail: String? = nil, steps: [PersonStep]? = nil, firstName: String? = nil, lastName: String? = nil, partnerUserId: String? = nil, preferredLocale: String? = nil, rewards: [PersonReward]? = nil, publicData: [String:String]? = nil, shareables: [Shareable]? = nil, privateData: [String:String]? = nil, recentRequestContexts: [RequestContext]? = nil, displacedPersonId: String? = nil, blocked: Bool? = nil) {
        self.recentAssociatedFriends = recentAssociatedFriends
        self.recentAssociatedAdvocates = recentAssociatedAdvocates
        self._id = _id
        self.locale = locale
        self.data = data
        self.email = email
        self.normalizedEmail = normalizedEmail
        self.steps = steps
        self.firstName = firstName
        self.lastName = lastName
        self.partnerUserId = partnerUserId
        self.preferredLocale = preferredLocale
        self.rewards = rewards
        self.publicData = publicData
        self.shareables = shareables
        self.privateData = privateData
        self.recentRequestContexts = recentRequestContexts
        self.displacedPersonId = displacedPersonId
        self.blocked = blocked
    }

    public enum CodingKeys: String, CodingKey { 
        case recentAssociatedFriends
        case recentAssociatedAdvocates
        case _id = "id"
        case locale
        case data
        case email
        case normalizedEmail
        case steps
        case firstName
        case lastName
        case partnerUserId
        case preferredLocale
        case rewards
        case publicData
        case shareables
        case privateData
        case recentRequestContexts
        case displacedPersonId
        case blocked
    }

}
