//
// Person.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Person: Codable {

    public var locale: String?
    public var data: [String:String]?
    public var _id: String?
    public var normalizedEmail: String?
    public var email: String?
    public var steps: [PersonStep]?
    public var firstName: String?
    public var lastName: String?
    public var partnerUserId: String?
    public var preferredLocale: String?
    public var shareables: [Shareable]?
    public var rewards: [PersonReward]?
    public var publicData: [String:String]?
    public var recentRequestContexts: [RequestContext]?
    public var privateData: [String:String]?
    public var displacedPersonId: String?
    public var blocked: Bool?
    public var recentAssociatedFriends: [PersonReferral]?
    public var recentAssociatedAdvocates: [PersonReferral]?

    public init(locale: String? = nil, data: [String:String]? = nil, _id: String? = nil, normalizedEmail: String? = nil, email: String? = nil, steps: [PersonStep]? = nil, firstName: String? = nil, lastName: String? = nil, partnerUserId: String? = nil, preferredLocale: String? = nil, shareables: [Shareable]? = nil, rewards: [PersonReward]? = nil, publicData: [String:String]? = nil, recentRequestContexts: [RequestContext]? = nil, privateData: [String:String]? = nil, displacedPersonId: String? = nil, blocked: Bool? = nil, recentAssociatedFriends: [PersonReferral]? = nil, recentAssociatedAdvocates: [PersonReferral]? = nil) {
        self.locale = locale
        self.data = data
        self._id = _id
        self.normalizedEmail = normalizedEmail
        self.email = email
        self.steps = steps
        self.firstName = firstName
        self.lastName = lastName
        self.partnerUserId = partnerUserId
        self.preferredLocale = preferredLocale
        self.shareables = shareables
        self.rewards = rewards
        self.publicData = publicData
        self.recentRequestContexts = recentRequestContexts
        self.privateData = privateData
        self.displacedPersonId = displacedPersonId
        self.blocked = blocked
        self.recentAssociatedFriends = recentAssociatedFriends
        self.recentAssociatedAdvocates = recentAssociatedAdvocates
    }

    public enum CodingKeys: String, CodingKey { 
        case locale
        case data
        case _id = "id"
        case normalizedEmail
        case email
        case steps
        case firstName
        case lastName
        case partnerUserId
        case preferredLocale
        case shareables
        case rewards
        case publicData
        case recentRequestContexts
        case privateData
        case displacedPersonId
        case blocked
        case recentAssociatedFriends
        case recentAssociatedAdvocates
    }

}
