//
// Person.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Person: Codable {

    public var locale: String?
    public var _id: String?
    public var data: [String:String]?
    public var email: String?
    public var normalizedEmail: String?
    public var steps: [PersonStep]?
    public var firstName: String?
    public var lastName: String?
    public var partnerUserId: String?
    public var preferredLocale: String?
    public var shareables: [Shareable]?
    public var rewards: [PersonReward]?
    public var publicData: [String:String]?
    public var privateData: [String:String]?
    public var recentRequestContexts: [RequestContext]?
    public var recentAssociatedFriends: [PersonReferral]?
    public var recentAssociatedAdvocates: [PersonReferral]?
    public var displacedPersonId: String?
    public var blocked: Bool?

    public init(locale: String? = nil, _id: String? = nil, data: [String:String]? = nil, email: String? = nil, normalizedEmail: String? = nil, steps: [PersonStep]? = nil, firstName: String? = nil, lastName: String? = nil, partnerUserId: String? = nil, preferredLocale: String? = nil, shareables: [Shareable]? = nil, rewards: [PersonReward]? = nil, publicData: [String:String]? = nil, privateData: [String:String]? = nil, recentRequestContexts: [RequestContext]? = nil, recentAssociatedFriends: [PersonReferral]? = nil, recentAssociatedAdvocates: [PersonReferral]? = nil, displacedPersonId: String? = nil, blocked: Bool? = nil) {
        self.locale = locale
        self._id = _id
        self.data = data
        self.email = email
        self.normalizedEmail = normalizedEmail
        self.steps = steps
        self.firstName = firstName
        self.lastName = lastName
        self.partnerUserId = partnerUserId
        self.preferredLocale = preferredLocale
        self.shareables = shareables
        self.rewards = rewards
        self.publicData = publicData
        self.privateData = privateData
        self.recentRequestContexts = recentRequestContexts
        self.recentAssociatedFriends = recentAssociatedFriends
        self.recentAssociatedAdvocates = recentAssociatedAdvocates
        self.displacedPersonId = displacedPersonId
        self.blocked = blocked
    }

    public enum CodingKeys: String, CodingKey { 
        case locale
        case _id = "id"
        case data
        case email
        case normalizedEmail
        case steps
        case firstName
        case lastName
        case partnerUserId
        case preferredLocale
        case shareables
        case rewards
        case publicData
        case privateData
        case recentRequestContexts
        case recentAssociatedFriends
        case recentAssociatedAdvocates
        case displacedPersonId
        case blocked
    }

}
