//
// PersonJourney.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonJourney: Codable {

    public var data: [String:String]?
    public var container: String?
    public var campaignId: String?
    public var journeyType: String?
    public var publicData: [String:String]?
    public var privateData: [String:String]?

    public init(data: [String:String]? = nil, container: String? = nil, campaignId: String? = nil, journeyType: String? = nil, publicData: [String:String]? = nil, privateData: [String:String]? = nil) {
        self.data = data
        self.container = container
        self.campaignId = campaignId
        self.journeyType = journeyType
        self.publicData = publicData
        self.privateData = privateData
    }


}
