//
// PersonReferral.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonReferral: Codable {

    public var reason: String?
    public var container: String?
    public var clientId: String?
    public var createdDate: String?
    public var otherPersonId: String?
    public var updatedDate: String?
    public var mySide: String?
    public var displaced: Bool?

    public init(reason: String? = nil, container: String? = nil, clientId: String? = nil, createdDate: String? = nil, otherPersonId: String? = nil, updatedDate: String? = nil, mySide: String? = nil, displaced: Bool? = nil) {
        self.reason = reason
        self.container = container
        self.clientId = clientId
        self.createdDate = createdDate
        self.otherPersonId = otherPersonId
        self.updatedDate = updatedDate
        self.mySide = mySide
        self.displaced = displaced
    }


}
