//
// PollingRewardResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PollingRewardResponse: Codable {

    public enum Status: String, Codable { 
        case pending = "PENDING"
        case succeeded = "SUCCEEDED"
        case failed = "FAILED"
    }
    public var reward: RewardResponse?
    public var status: Status?
    public var qualityResults: [QualityResults]?

    public init(reward: RewardResponse? = nil, status: Status? = nil, qualityResults: [QualityResults]? = nil) {
        self.reward = reward
        self.status = status
        self.qualityResults = qualityResults
    }

    public enum CodingKeys: String, CodingKey { 
        case reward
        case status
        case qualityResults = "quality_results"
    }

}
