//
// PrehandlerConditionContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PrehandlerConditionContext: Codable {

    public var processedRawEvent: ProcessedRawEvent?
    public var rawEvent: RawEvent?
    public var candidatePerson: Person?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(processedRawEvent: ProcessedRawEvent? = nil, rawEvent: RawEvent? = nil, candidatePerson: Person? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.processedRawEvent = processedRawEvent
        self.rawEvent = rawEvent
        self.candidatePerson = candidatePerson
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
