//
// ProcessedRawEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProcessedRawEvent: Codable {

    public var verifiedData: [String:String]?
    public var allData: [EventData]?
    public var data: [String:String]?
    public var clientDomain: PublicClientDomain?
    public var eventName: String?
    public var sandbox: Sandbox?
    public var eventTime: String?
    public var sourceGeoIps: [GeoIp]?
    public var deviceId: String?
    public var pageId: String?
    public var appType: String?
    public var appData: [String:String]?

    public init(verifiedData: [String:String]? = nil, allData: [EventData]? = nil, data: [String:String]? = nil, clientDomain: PublicClientDomain? = nil, eventName: String? = nil, sandbox: Sandbox? = nil, eventTime: String? = nil, sourceGeoIps: [GeoIp]? = nil, deviceId: String? = nil, pageId: String? = nil, appType: String? = nil, appData: [String:String]? = nil) {
        self.verifiedData = verifiedData
        self.allData = allData
        self.data = data
        self.clientDomain = clientDomain
        self.eventName = eventName
        self.sandbox = sandbox
        self.eventTime = eventTime
        self.sourceGeoIps = sourceGeoIps
        self.deviceId = deviceId
        self.pageId = pageId
        self.appType = appType
        self.appData = appData
    }


}
