//
// PublicClientDomainService.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicClientDomainService: Codable {

    public var publicClientDomains: [PublicClientDomain]?

    public init(publicClientDomains: [PublicClientDomain]? = nil) {
        self.publicClientDomains = publicClientDomains
    }


}
