//
// QualityResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QualityResults: Codable {

    public enum Score: String, Codable { 
        case error = "ERROR"
        case low = "LOW"
        case high = "HIGH"
    }
    public var score: Score?
    public var qualityRuleResults: [QualityRuleResult]?

    public init(score: Score? = nil, qualityRuleResults: [QualityRuleResult]? = nil) {
        self.score = score
        self.qualityRuleResults = qualityRuleResults
    }

    public enum CodingKeys: String, CodingKey { 
        case score
        case qualityRuleResults = "quality_rule_results"
    }

}
