//
// QualityRuleResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QualityRuleResult: Codable {

    public enum Score: String, Codable { 
        case error = "ERROR"
        case low = "LOW"
        case high = "HIGH"
    }
    public var ruleName: String?
    public var score: Score?

    public init(ruleName: String? = nil, score: Score? = nil) {
        self.ruleName = ruleName
        self.score = score
    }

    public enum CodingKeys: String, CodingKey { 
        case ruleName = "rule_name"
        case score
    }

}
