//
// RawEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RawEvent: Codable {

    public var httpRequestMethod: String?
    public var rawEventId: String?
    public var referrer: String?
    public var eventName: String?
    public var url: String?
    public var httpHeaders: [String:[String]]?
    public var httpCookies: [String:[String]]?
    public var httpParameters: [String:[String]]?
    public var apiType: String?
    public var httpRequestBody: String?
    public var requestTime: String?
    public var clientDomainContext: ClientDomainContext?
    public var sourceIps: [String]?

    public init(httpRequestMethod: String? = nil, rawEventId: String? = nil, referrer: String? = nil, eventName: String? = nil, url: String? = nil, httpHeaders: [String:[String]]? = nil, httpCookies: [String:[String]]? = nil, httpParameters: [String:[String]]? = nil, apiType: String? = nil, httpRequestBody: String? = nil, requestTime: String? = nil, clientDomainContext: ClientDomainContext? = nil, sourceIps: [String]? = nil) {
        self.httpRequestMethod = httpRequestMethod
        self.rawEventId = rawEventId
        self.referrer = referrer
        self.eventName = eventName
        self.url = url
        self.httpHeaders = httpHeaders
        self.httpCookies = httpCookies
        self.httpParameters = httpParameters
        self.apiType = apiType
        self.httpRequestBody = httpRequestBody
        self.requestTime = requestTime
        self.clientDomainContext = clientDomainContext
        self.sourceIps = sourceIps
    }


}
