//
// ReportTypeParameterDetailsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportTypeParameterDetailsRequest: Codable {

    public var name: String?
    public var displayName: String?
    public var order: Int?
    public var category: String?
    public var defaultValue: String?

    public init(name: String? = nil, displayName: String? = nil, order: Int? = nil, category: String? = nil, defaultValue: String? = nil) {
        self.name = name
        self.displayName = displayName
        self.order = order
        self.category = category
        self.defaultValue = defaultValue
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case displayName = "display_name"
        case order
        case category
        case defaultValue = "default_value"
    }

}
