//
// ReportTypeParameterDetailsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportTypeParameterDetailsResponse: Codable {

    public var name: String?
    public var displayName: String?
    public var category: String?
    public var type: ReportParameterTypeResponse?
    public var isRequired: Bool?
    public var order: Int?
    public var defaultValue: String?

    public init(name: String? = nil, displayName: String? = nil, category: String? = nil, type: ReportParameterTypeResponse? = nil, isRequired: Bool? = nil, order: Int? = nil, defaultValue: String? = nil) {
        self.name = name
        self.displayName = displayName
        self.category = category
        self.type = type
        self.isRequired = isRequired
        self.order = order
        self.defaultValue = defaultValue
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case displayName = "display_name"
        case category
        case type
        case isRequired = "is_required"
        case order
        case defaultValue = "default_value"
    }

}
