//
// ReportRunnerResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportRunnerResponse: Codable {

    public enum Formats: String, Codable { 
        case json = "JSON"
        case csv = "CSV"
        case xlsx = "XLSX"
        case psv = "PSV"
        case headlessCsv = "HEADLESS_CSV"
        case headlessPsv = "HEADLESS_PSV"
    }
    public enum Scopes: String, Codable { 
        case clientSuperuser = "CLIENT_SUPERUSER"
        case clientAdmin = "CLIENT_ADMIN"
        case consumerPublic = "CONSUMER_PUBLIC"
    }
    public var _id: String?
    public var name: String?
    public var reportTypeName: String?
    public var formats: [Formats]?
    public var createdDate: Date?
    public var updatedDate: Date?
    public var parameters: [String:ReportParameterResponse]?
    public var scopes: [Scopes]?
    public var tags: [String]?
    public var userId: String?
    public var sftpServerId: String?
    public var type: String?

    public init(_id: String? = nil, name: String? = nil, reportTypeName: String? = nil, formats: [Formats]? = nil, createdDate: Date? = nil, updatedDate: Date? = nil, parameters: [String:ReportParameterResponse]? = nil, scopes: [Scopes]? = nil, tags: [String]? = nil, userId: String? = nil, sftpServerId: String? = nil, type: String? = nil) {
        self._id = _id
        self.name = name
        self.reportTypeName = reportTypeName
        self.formats = formats
        self.createdDate = createdDate
        self.updatedDate = updatedDate
        self.parameters = parameters
        self.scopes = scopes
        self.tags = tags
        self.userId = userId
        self.sftpServerId = sftpServerId
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case reportTypeName = "report_type_name"
        case formats
        case createdDate = "created_date"
        case updatedDate = "updated_date"
        case parameters
        case scopes
        case tags
        case userId = "user_id"
        case sftpServerId = "sftp_server_id"
        case type
    }

}
