//
// ReportTypeWithClientsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportTypeWithClientsResponse: Codable {

    public var reportType: ReportTypeResponse?
    public var clientIds: [String]?

    public init(reportType: ReportTypeResponse? = nil, clientIds: [String]? = nil) {
        self.reportType = reportType
        self.clientIds = clientIds
    }

    public enum CodingKeys: String, CodingKey { 
        case reportType = "report_type"
        case clientIds = "client_ids"
    }

}
