//
// ReportTypeColumnResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportTypeColumnResponse: Codable {

    public var name: String?
    public var sampleValue: String?
    public var note: String?

    public init(name: String? = nil, sampleValue: String? = nil, note: String? = nil) {
        self.name = name
        self.sampleValue = sampleValue
        self.note = note
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case sampleValue = "sample_value"
        case note
    }

}
