//
// ReportParameterResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportParameterResponse: Codable {

    public var value: String?
    public var details: ReportParameterDetailsResponse?

    public init(value: String? = nil, details: ReportParameterDetailsResponse? = nil) {
        self.value = value
        self.details = details
    }


}
