//
// ReportParameterTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportParameterTypeResponse: Codable {

    public enum Name: String, Codable { 
        case boolean = "BOOLEAN"
        case string = "STRING"
        case stringList = "STRING_LIST"
        case integer = "INTEGER"
        case date = "DATE"
        case dateRange = "DATE_RANGE"
        case time = "TIME"
        case timeRange = "TIME_RANGE"
        case _enum = "ENUM"
        case enumList = "ENUM_LIST"
        case campaignId = "CAMPAIGN_ID"
        case programLabel = "PROGRAM_LABEL"
        case steps = "STEPS"
        case step = "STEP"
        case regex = "REGEX"
        case long = "LONG"
        case clientId = "CLIENT_ID"
        case stepColumnList = "STEP_COLUMN_LIST"
        case normalizedEmail = "NORMALIZED_EMAIL"
        case channelMapping = "CHANNEL_MAPPING"
        case flows = "FLOWS"
        case tiers = "TIERS"
        case rowMappings = "ROW_MAPPINGS"
        case personMappings = "PERSON_MAPPINGS"
        case filterMappings = "FILTER_MAPPINGS"
        case sortOrderMappings = "SORT_ORDER_MAPPINGS"
        case personDimensionMappings = "PERSON_DIMENSION_MAPPINGS"
        case metricMappings = "METRIC_MAPPINGS"
        case emailNames = "EMAIL_NAMES"
        case granularTimeRange = "GRANULAR_TIME_RANGE"
    }
    public var name: Name?
    public var values: [String]?

    public init(name: Name? = nil, values: [String]? = nil) {
        self.name = name
        self.values = values
    }


}
