//
// ReportTypeTagRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReportTypeTagRequest: Codable {

    public enum ModelType: String, Codable { 
        case global = "GLOBAL"
        case _private = "PRIVATE"
    }
    public var name: String?
    public var type: ModelType?

    public init(name: String? = nil, type: ModelType? = nil) {
        self.name = name
        self.type = type
    }


}
