//
// RequestContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestContext: Codable {

    public var ip: String?
    public var deviceId: String?
    public var geoIp: GeoIp?
    public var createdAt: String?

    public init(ip: String? = nil, deviceId: String? = nil, geoIp: GeoIp? = nil, createdAt: String? = nil) {
        self.ip = ip
        self.deviceId = deviceId
        self.geoIp = geoIp
        self.createdAt = createdAt
    }


}
