//
// RestExceptionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents the API error response */

public struct RestExceptionResponse: Codable {

    /** Unique id associated with this error, useful for discussions with Extole */
    public var uniqueId: String?
    /** HTTP status code that was returned with this error, useful if client get response code */
    public var httpStatusCode: Int?
    /** Specific error code for this error type, documented per endpoint */
    public var code: String?
    /** User readable English description of the error */
    public var message: String?
    /** Attributes related to the error, varies be error code, documented per endpoint */
    public var parameters: [String:Entry?]?

    public init(uniqueId: String? = nil, httpStatusCode: Int? = nil, code: String? = nil, message: String? = nil, parameters: [String:Entry?]? = nil) {
        self.uniqueId = uniqueId
        self.httpStatusCode = httpStatusCode
        self.code = code
        self.message = message
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey { 
        case uniqueId = "unique_id"
        case httpStatusCode = "http_status_code"
        case code
        case message
        case parameters
    }

}
