//
// RewardContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RewardContext: Codable {

    public var valueOfRewardedEvent: Decimal?
    public var slots: [String]?
    public var name: String?
    public var partnerRewardId: String?
    public var faceValue: Decimal?
    public var faceValueType: String?
    public var rewardId: String?
    public var tags: [String]?

    public init(valueOfRewardedEvent: Decimal? = nil, slots: [String]? = nil, name: String? = nil, partnerRewardId: String? = nil, faceValue: Decimal? = nil, faceValueType: String? = nil, rewardId: String? = nil, tags: [String]? = nil) {
        self.valueOfRewardedEvent = valueOfRewardedEvent
        self.slots = slots
        self.name = name
        self.partnerRewardId = partnerRewardId
        self.faceValue = faceValue
        self.faceValueType = faceValueType
        self.rewardId = rewardId
        self.tags = tags
    }


}
