//
// RewardRuleContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RewardRuleContext: Codable {

    public var resultBuilder: EvaluationResultBuilder?
    public var person: Person?
    public var event: ConsumerEvent?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(resultBuilder: EvaluationResultBuilder? = nil, person: Person? = nil, event: ConsumerEvent? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.resultBuilder = resultBuilder
        self.person = person
        self.event = event
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
