//
// RewardConsumerEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RewardConsumerEvent: Codable {

    public var rewardState: String?
    public var reward: RewardContext?
    public var labels: [String]?
    public var name: String?
    public var campaignId: String?
    public var data: [String:String]?
    public var _id: String?
    public var type: String?
    public var person: Person?
    public var sandbox: Sandbox?
    public var clientContext: ClientContext?
    public var eventTime: String?
    public var requestTime: String?
    public var causeEventId: String?
    public var rootEventId: String?
    public var eventContext: EventContext?
    public var clientDomainContext: ClientDomainContext?

    public init(rewardState: String? = nil, reward: RewardContext? = nil, labels: [String]? = nil, name: String? = nil, campaignId: String? = nil, data: [String:String]? = nil, _id: String? = nil, type: String? = nil, person: Person? = nil, sandbox: Sandbox? = nil, clientContext: ClientContext? = nil, eventTime: String? = nil, requestTime: String? = nil, causeEventId: String? = nil, rootEventId: String? = nil, eventContext: EventContext? = nil, clientDomainContext: ClientDomainContext? = nil) {
        self.rewardState = rewardState
        self.reward = reward
        self.labels = labels
        self.name = name
        self.campaignId = campaignId
        self.data = data
        self._id = _id
        self.type = type
        self.person = person
        self.sandbox = sandbox
        self.clientContext = clientContext
        self.eventTime = eventTime
        self.requestTime = requestTime
        self.causeEventId = causeEventId
        self.rootEventId = rootEventId
        self.eventContext = eventContext
        self.clientDomainContext = clientDomainContext
    }

    public enum CodingKeys: String, CodingKey { 
        case rewardState
        case reward
        case labels
        case name
        case campaignId
        case data
        case _id = "id"
        case type
        case person
        case sandbox
        case clientContext
        case eventTime
        case requestTime
        case causeEventId
        case rootEventId
        case eventContext
        case clientDomainContext
    }

}
