//
// Sandbox.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Sandbox: Codable {

    public var container: String?
    public var sandbox: String?
    public var sandboxId: String?

    public init(container: String? = nil, sandbox: String? = nil, sandboxId: String? = nil) {
        self.container = container
        self.sandbox = sandbox
        self.sandboxId = sandboxId
    }


}
