//
// ScheduledReportRunnerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScheduledReportRunnerRequest: Codable {

    public enum ModelType: String, Codable { 
        case scheduled = "SCHEDULED"
        case refreshing = "REFRESHING"
    }
    public enum Formats: String, Codable { 
        case json = "JSON"
        case csv = "CSV"
        case xlsx = "XLSX"
        case psv = "PSV"
        case headlessCsv = "HEADLESS_CSV"
        case headlessPsv = "HEADLESS_PSV"
    }
    public enum Scopes: String, Codable { 
        case clientSuperuser = "CLIENT_SUPERUSER"
        case clientAdmin = "CLIENT_ADMIN"
        case consumerPublic = "CONSUMER_PUBLIC"
    }
    public enum Frequency: String, Codable { 
        case hourly = "HOURLY"
        case daily = "DAILY"
        case weekly = "WEEKLY"
        case monthly = "MONTHLY"
        case quarterly = "QUARTERLY"
        case login = "LOGIN"
    }
    public var type: ModelType?
    public var name: String?
    public var reportType: String?
    public var formats: [Formats]?
    public var parameters: [String:String]?
    public var tags: [String]?
    public var scopes: [Scopes]?
    public var sftpServerId: String?
    public var frequency: Frequency?
    public var scheduleStartDate: Date?
    public var legacySftpReportNameFormat: Bool?

    public init(type: ModelType? = nil, name: String? = nil, reportType: String? = nil, formats: [Formats]? = nil, parameters: [String:String]? = nil, tags: [String]? = nil, scopes: [Scopes]? = nil, sftpServerId: String? = nil, frequency: Frequency? = nil, scheduleStartDate: Date? = nil, legacySftpReportNameFormat: Bool? = nil) {
        self.type = type
        self.name = name
        self.reportType = reportType
        self.formats = formats
        self.parameters = parameters
        self.tags = tags
        self.scopes = scopes
        self.sftpServerId = sftpServerId
        self.frequency = frequency
        self.scheduleStartDate = scheduleStartDate
        self.legacySftpReportNameFormat = legacySftpReportNameFormat
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case name
        case reportType = "report_type"
        case formats
        case parameters
        case tags
        case scopes
        case sftpServerId = "sftp_server_id"
        case frequency
        case scheduleStartDate = "schedule_start_date"
        case legacySftpReportNameFormat = "legacy_sftp_report_name_format"
    }

}
