//
// ScheduledReportRunnerResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScheduledReportRunnerResponse: Codable {

    public enum Formats: String, Codable { 
        case json = "JSON"
        case csv = "CSV"
        case xlsx = "XLSX"
        case psv = "PSV"
        case headlessCsv = "HEADLESS_CSV"
        case headlessPsv = "HEADLESS_PSV"
    }
    public enum Scopes: String, Codable { 
        case clientSuperuser = "CLIENT_SUPERUSER"
        case clientAdmin = "CLIENT_ADMIN"
        case consumerPublic = "CONSUMER_PUBLIC"
    }
    public enum Frequency: String, Codable { 
        case hourly = "HOURLY"
        case daily = "DAILY"
        case weekly = "WEEKLY"
        case monthly = "MONTHLY"
        case quarterly = "QUARTERLY"
        case login = "LOGIN"
    }
    public var _id: String?
    public var name: String?
    public var reportTypeName: String?
    public var formats: [Formats]?
    public var createdDate: Date?
    public var updatedDate: Date?
    public var parameters: [String:ReportParameterResponse]?
    public var scopes: [Scopes]?
    public var tags: [String]?
    public var userId: String?
    public var sftpServerId: String?
    public var type: String?
    public var frequency: Frequency?
    public var scheduleStartDate: Date?
    public var legacySftpReportNameFormat: Bool?

    public init(_id: String? = nil, name: String? = nil, reportTypeName: String? = nil, formats: [Formats]? = nil, createdDate: Date? = nil, updatedDate: Date? = nil, parameters: [String:ReportParameterResponse]? = nil, scopes: [Scopes]? = nil, tags: [String]? = nil, userId: String? = nil, sftpServerId: String? = nil, type: String? = nil, frequency: Frequency? = nil, scheduleStartDate: Date? = nil, legacySftpReportNameFormat: Bool? = nil) {
        self._id = _id
        self.name = name
        self.reportTypeName = reportTypeName
        self.formats = formats
        self.createdDate = createdDate
        self.updatedDate = updatedDate
        self.parameters = parameters
        self.scopes = scopes
        self.tags = tags
        self.userId = userId
        self.sftpServerId = sftpServerId
        self.type = type
        self.frequency = frequency
        self.scheduleStartDate = scheduleStartDate
        self.legacySftpReportNameFormat = legacySftpReportNameFormat
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case reportTypeName = "report_type_name"
        case formats
        case createdDate = "created_date"
        case updatedDate = "updated_date"
        case parameters
        case scopes
        case tags
        case userId = "user_id"
        case sftpServerId = "sftp_server_id"
        case type
        case frequency
        case scheduleStartDate = "schedule_start_date"
        case legacySftpReportNameFormat = "legacy_sftp_report_name_format"
    }

}
