//
// SelectedCampaignContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SelectedCampaignContext: Codable {

    public var campaignState: String?
    public var quality: String?
    public var campaignId: String?
    public var programLabel: String?
    public var triggerResults: [StepConsumerEventTriggerResult]?
    public var campaignVersion: Int?

    public init(campaignState: String? = nil, quality: String? = nil, campaignId: String? = nil, programLabel: String? = nil, triggerResults: [StepConsumerEventTriggerResult]? = nil, campaignVersion: Int? = nil) {
        self.campaignState = campaignState
        self.quality = quality
        self.campaignId = campaignId
        self.programLabel = programLabel
        self.triggerResults = triggerResults
        self.campaignVersion = campaignVersion
    }


}
