//
// ShareableWithLink.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShareableWithLink: Codable {

    public var link: String?
    public var key: String?
    public var _id: String?
    public var content: ShareableContent?
    public var data: [String:String]?
    public var label: String?
    public var code: String?
    public var clientDomainId: String?

    public init(link: String? = nil, key: String? = nil, _id: String? = nil, content: ShareableContent? = nil, data: [String:String]? = nil, label: String? = nil, code: String? = nil, clientDomainId: String? = nil) {
        self.link = link
        self.key = key
        self._id = _id
        self.content = content
        self.data = data
        self.label = label
        self.code = code
        self.clientDomainId = clientDomainId
    }

    public enum CodingKeys: String, CodingKey { 
        case link
        case key
        case _id = "id"
        case content
        case data
        case label
        case code
        case clientDomainId
    }

}
