//
// ShareableContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ShareableContent: Codable {

    public var _description: String?
    public var partnerContentId: String?
    public var title: String?
    public var imageUrl: String?
    public var url: String?

    public init(_description: String? = nil, partnerContentId: String? = nil, title: String? = nil, imageUrl: String? = nil, url: String? = nil) {
        self._description = _description
        self.partnerContentId = partnerContentId
        self.title = title
        self.imageUrl = imageUrl
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case partnerContentId
        case title
        case imageUrl
        case url
    }

}
