//
// State.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct State: Codable {

    public var name: String?
    public var isoCode: String?

    public init(name: String? = nil, isoCode: String? = nil) {
        self.name = name
        self.isoCode = isoCode
    }


}
