//
// StepConsumerEventTriggerResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StepConsumerEventTriggerResult: Codable {

    public enum TriggerPhase: String, Codable { 
        case matching = "MATCHING"
        case qualifying = "QUALIFYING"
        case quality = "QUALITY"
    }
    public var name: String?
    public var logMessages: [String]?
    public var triggerId: String?
    public var triggerType: String?
    public var triggerPhase: TriggerPhase?
    public var passed: Bool?

    public init(name: String? = nil, logMessages: [String]? = nil, triggerId: String? = nil, triggerType: String? = nil, triggerPhase: TriggerPhase? = nil, passed: Bool? = nil) {
        self.name = name
        self.logMessages = logMessages
        self.triggerId = triggerId
        self.triggerType = triggerType
        self.triggerPhase = triggerPhase
        self.passed = passed
    }


}
