//
// StepDataContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StepDataContext: Codable {

    public var referralSource: String?
    public var channel: String?
    public var person: Person?
    public var event: ConsumerEvent?
    public var otherPerson: Person?
    public var journey: PersonJourney?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(referralSource: String? = nil, channel: String? = nil, person: Person? = nil, event: ConsumerEvent? = nil, otherPerson: Person? = nil, journey: PersonJourney? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.referralSource = referralSource
        self.channel = channel
        self.person = person
        self.event = event
        self.otherPerson = otherPerson
        self.journey = journey
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
