//
// StepHasPriorStepTriggerContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StepHasPriorStepTriggerContext: Codable {

    public var step: PersonStep?
    public var person: Person?
    public var targetingContext: TargetingContext?
    public var causeEvent: ConsumerEvent?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(step: PersonStep? = nil, person: Person? = nil, targetingContext: TargetingContext? = nil, causeEvent: ConsumerEvent? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.step = step
        self.person = person
        self.targetingContext = targetingContext
        self.causeEvent = causeEvent
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
