//
// StepConsumerEventTriggerPhase.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum StepConsumerEventTriggerPhase: String, Codable {
    case matching = "MATCHING"
    case qualifying = "QUALIFYING"
    case quality = "QUALITY"
}