//
// SubmitEventRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubmitEventRequest: Codable {

    public var eventName: String?
    public var jwt: String?
    public var idToken: String?
    public var data: [String:String]?

    public init(eventName: String? = nil, jwt: String? = nil, idToken: String? = nil, data: [String:String]? = nil) {
        self.eventName = eventName
        self.jwt = jwt
        self.idToken = idToken
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case eventName = "event_name"
        case jwt
        case idToken = "id_token"
        case data
    }

}
