//
// TargetingContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TargetingContext: Codable {

    public var referral: PersonReferral?

    public init(referral: PersonReferral? = nil) {
        self.referral = referral
    }


}
