//
// TokenV4Response.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenV4Response: Codable {

    public enum Scopes: String, Codable { 
        case verifiedConsumer = "VERIFIED_CONSUMER"
        case updateProfile = "UPDATE_PROFILE"
    }
    public enum Capabilities: String, Codable { 
        case verifiedConsumer = "VERIFIED_CONSUMER"
        case updateProfile = "UPDATE_PROFILE"
    }
    public var accessToken: String?
    public var expiresIn: Int64?
    public var scopes: [Scopes]?
    public var capabilities: [Capabilities]?

    public init(accessToken: String? = nil, expiresIn: Int64? = nil, scopes: [Scopes]? = nil, capabilities: [Capabilities]? = nil) {
        self.accessToken = accessToken
        self.expiresIn = expiresIn
        self.scopes = scopes
        self.capabilities = capabilities
    }

    public enum CodingKeys: String, CodingKey { 
        case accessToken = "access_token"
        case expiresIn = "expires_in"
        case scopes
        case capabilities
    }

}
