//
// TokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenResponse: Codable {

    public enum Scopes: String, Codable { 
        case verifiedConsumer = "VERIFIED_CONSUMER"
        case updateProfile = "UPDATE_PROFILE"
    }
    public var accessToken: String?
    public var expiresIn: Int64?
    public var scopes: [Scopes]?

    public init(accessToken: String? = nil, expiresIn: Int64? = nil, scopes: [Scopes]? = nil) {
        self.accessToken = accessToken
        self.expiresIn = expiresIn
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey { 
        case accessToken = "access_token"
        case expiresIn = "expires_in"
        case scopes
    }

}
