//
// UnsubscribeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UnsubscribeResponse: Codable {

    public var unsubscribed: Bool?

    public init(unsubscribed: Bool? = nil) {
        self.unsubscribed = unsubscribed
    }


}
