//
// WebhookContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WebhookContext: Codable {

    public var data: [String:String]?
    public var webhook: Webhook?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(data: [String:String]? = nil, webhook: Webhook? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.data = data
        self.webhook = webhook
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
