//
// WebhookEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WebhookEvent: Codable {

    public var causeEventSequence: Int?
    public var deviceProfileId: String?
    public var identityProfileId: String?
    public var data: [String:String]?
    public var clientDomain: String?
    public var campaignId: String?
    public var programLabel: String?
    public var eventId: String?
    public var eventTime: String?
    public var causeEventId: String?
    public var rootEventId: String?
    public var clientDomainId: String?
    public var webhookId: String?

    public init(causeEventSequence: Int? = nil, deviceProfileId: String? = nil, identityProfileId: String? = nil, data: [String:String]? = nil, clientDomain: String? = nil, campaignId: String? = nil, programLabel: String? = nil, eventId: String? = nil, eventTime: String? = nil, causeEventId: String? = nil, rootEventId: String? = nil, clientDomainId: String? = nil, webhookId: String? = nil) {
        self.causeEventSequence = causeEventSequence
        self.deviceProfileId = deviceProfileId
        self.identityProfileId = identityProfileId
        self.data = data
        self.clientDomain = clientDomain
        self.campaignId = campaignId
        self.programLabel = programLabel
        self.eventId = eventId
        self.eventTime = eventTime
        self.causeEventId = causeEventId
        self.rootEventId = rootEventId
        self.clientDomainId = clientDomainId
        self.webhookId = webhookId
    }


}
