//
// WebhookDispatchResultEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WebhookDispatchResultEvent: Codable {

    public var requestBody: String?
    public var responseBody: String?
    public var responseStatusCode: Int?
    public var responseHeaders: [String:[String]]?
    public var requestHeaders: [String:[String]]?

    public init(requestBody: String? = nil, responseBody: String? = nil, responseStatusCode: Int? = nil, responseHeaders: [String:[String]]? = nil, requestHeaders: [String:[String]]? = nil) {
        self.requestBody = requestBody
        self.responseBody = responseBody
        self.responseStatusCode = responseStatusCode
        self.responseHeaders = responseHeaders
        self.requestHeaders = requestHeaders
    }


}
