//
// WebhookActionContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WebhookActionContext: Codable {

    public var webhook: Webhook?
    public var stepEvent: StepConsumerEvent?
    public var person: Person?
    public var causeEvent: ConsumerEvent?
    public var globalServices: GlobalServices?
    public var clientContext: ClientContext?

    public init(webhook: Webhook? = nil, stepEvent: StepConsumerEvent? = nil, person: Person? = nil, causeEvent: ConsumerEvent? = nil, globalServices: GlobalServices? = nil, clientContext: ClientContext? = nil) {
        self.webhook = webhook
        self.stepEvent = stepEvent
        self.person = person
        self.causeEvent = causeEvent
        self.globalServices = globalServices
        self.clientContext = clientContext
    }


}
